# Generated by Django 4.0.3 on 2022-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default='HelloWorld', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='John Doe', max_length=200),
        ),
    ]
