# Generated by Django 4.0.3 on 2022-04-18 13:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_auth0user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendlist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=1000, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
