# Generated by Django 4.0.3 on 2022-04-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_auth0user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default='HelloWorld', max_length=500),
        ),
    ]
