# Generated by Django 4.0.3 on 2022-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0004_alter_user_age_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='John Doe', max_length=200),
        ),
    ]
